version: '3.8'

services:
  movie-theater-db:
    image: mongo:latest
    container_name: movie-theater-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: movie-theater-admin
      MONGO_INITDB_ROOT_PASSWORD: express123
      MONGO_INITDB_DATABASE: movie-theater-db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: